schema_version = "1.0.0"

id = "textools"
version = "1.6.7"
name = "TexTools"
tagline = "Professional UV and Texture tools for Blender."
type = "add-on"

maintainer = "renderhjs, franMarz, Sav Martin"
# This is UNNOFFICIAL COMMUNITY FORK
website = "https://github.com/unclepomedev/TexTools-Blender"


blender_version_min = "5.0.0"

license = [
    "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Required for baking textures and saving/loading images."
